services:
  mysql:
    image: mysql:8.0
    container_name: day04-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_db
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql_day04_data:/var/lib/mysql

volumes:
  mysql_day04_data:
